### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Aleksandr-S** [bakwc/LibQtScreen#1]
Отличная работа, очень интересные решения, много узнал нового.

Столкнулся с проблемой. Если screener скомпилирован в конфигурации “Release”, то Q_ASSERT не работает, и если не найдены helper и libqtscreen, то screener падает. Если не ошибаюсь, причина тому тут:
QList<QByteArray> lines = data.split('\n');
offsets.DX8PresentOffset = lines[0].trimmed().toInt();
offsets.DX9PresentOffset = lines[1].trimmed().toInt();
offsets.DX9PresentExOffset = lines[2].trimmed().toInt();
offsets.DXGIPresentOffset = lines[3].trimmed().toInt();

Для libqtscreen не хватает файла лога, без которого долго не мог понять, почему не устанавливается соединение с сервером. Оказалось, что игра должна быть запущена с правами администратора, иначе QLocalSocket  возвращает ошибку “Access denied ”.

Ещё заметил libqtscreen инжектится каждые 500 мс, в результате происходит утечка памяти в игровом приложении. Тут я не совсем разобрался в коде, возможно так и должно быть.
Кстати, если сделать скриншот и завершить приложение screener, затем заново его запустить скриншот уже не сделается, даже не появится сообщение "screenshot failed", причину пока не нашёл.

**Comment by bakwc** [comment]
Спасибо за репорт, создал отдельные таски: #2, #3, #4, #5

**Comment by bakwc** [comment]
"Оказалось, что игра должна быть запущена с правами администратора, иначе QLocalSocket возвращает ошибку “Access denied ”."
А можешь чуть подробней? У тебя screener был запущен без прав администратора, и игра тоже без прав администратора, но при этом была эта ошибка? Или screener с правами, а игра - без? Если второе, то почему скринер с правами администратора запускаешь?

**Comment by Aleksandr-S** [comment]
Запускаю Qt Creator по привычке с правами администратора, от куда запускаю screener. Запустил всё без прав администратора, соединение прошло, скрин сделался. 

Не знал о таком странном поведении QLocalSocket, есть решение - http://stackoverflow.com/questions/10719487/qlocalsocketconnecttoserver-failed-with-qlocalsocketsocketaccesserror-if-ser

**Comment by bakwc** [comment]
Ок, поправлю.

**Comment by bakwc** [comment]
А в целом - на разных играх нормально делается? Я его на нескольких тестил но может где-то не заскринить (или не в том формате снимок сделать). dll-ки используешь готовые или сам собрал? Под какой ос пробуешь?

**Comment by bakwc** [comment]
И насчет "если сделать скриншот и завершить приложение screener, затем заново его запустить". Ты уверен что screener был остановлен? По описанному тобой поведению складывается ощущение что первый screener не остановился, а была запущенна вторая копия.

**Comment by Aleksandr-S** [comment]
Библиотеки собрал сам, статические, что бы не копировать в игру Qt'шные либы. Пробую под windows 7 x64, либы и игра x32.
Тестировал, пока, на одной игре. 
В libQtSreen не хватает возможности создания скриншота рабочего стола. Скрин рабочего стола нужен для того, если игра запущена в окне.
 Как я вижу использование libQtSreen:
1.  Вызов функции поиска полноэкранного приложения, которая возвращает pid.
2.  Вызов MakeScreenshot с передачей в параметре pid.
3.  Если полноэкранное приложение не найдено (pid == 0), вызов функции создания скриншота рабочего стола (если необходимо).  (пример создание скриншота раб. стола на Qt, функция из двух строчек - http://doc.qt.io/qt-5/qtwidgets-desktop-screenshot-example.html).

Screener точно останавливается. Когда screener остановлен, либа продолжает работать – QlocalSocket при connectToServer выдаёт Invalid name, каждые 500 мс. Запускаю screener, либа подключается к серверу, посылает Info, но сервер почему-то не получает Info. Мне кажется, что в сетевом обмене, где-то проблема. Надо в нём разобраться, пока не понятно, зачем каждые 500 мс посылать Info, зачем Ping?

**Comment by bakwc** [comment]
Скрин рабочего стола в случае ошибки - хорошая идея, добавлю.
Скрин заданного процесса - надо подумать нужна ли такая функциональность и в каком виде.
Ping посылается для того, чтобы отследить отключение клиента. Info вроде посылается только один раз при старте / инжекте. Но ок, буду разбираться почему не работает при перезапуске.

**Comment by Aleksandr-S** [comment]
Как вариант - код получения pid в функции `void TScreenShotMaker::InjectAll()`, можно вынести в отдельную функцию, а `void TScreenShotMaker::MakeScreenshot()` изменить на `void TScreenShotMaker::MakeScreenshot(uint32_t pid)`. Обе функции сделать public, немного измениться интерфейс либы.

После `Sock.connectToServer("libqtscreen");` у тебя нет проверки на подключение, а сразу вызывается Send.  

``` c++
Sock.connectToServer("libqtscreen");
if(Sock.waitForConnected(1000)) {
        std::stringstream out;
        Info.Save(out);
        Send(NQtScreen::CMD_Info, QByteArray::fromStdString(out.str()));
} else {
            //qDebug() << "Error:" << Sock.errorString();
}
```

**Comment by bakwc** [comment]
Оу, точно - спасибо за фикс, сейчас залью.
По интерфейсу - имхо лучше тогда добавить метод InjectToPID, принимающий PID, который будет инжектить не обращая внимание на полноэкранность.

**Comment by Aleksandr-S** [comment]
Заодно измени немного функцию `GetOffsets` на

``` c++
...
QList<QByteArray> lines = data.split('\n');
if(lines.count() > 3) {
     offsets.DX8PresentOffset = lines[0].trimmed().toInt();
     offsets.DX9PresentOffset = lines[1].trimmed().toInt();
     offsets.DX9PresentExOffset = lines[2].trimmed().toInt();
     offsets.DXGIPresentOffset = lines[3].trimmed().toInt();
}
...
```

Не так критично, но всё же.

**Comment by bakwc** [comment]
ок, ты кстати сам можешь сделать fork и присылать pull реквесты (главное согласовать чтобы одно и то же не делать). Можешь в skype писать, мой filippfg.

**Comment by bakwc** [comment]
Работу после рестарта вроде зафиксил (проверь плиз), добавил возможность отключать авто-инъект, и инъектить в заданный процесс.
