### ISSUE TITLE
'fromStdString' is not a member of 'QByteArray'

### ISSUE THREAD

**Issue by DeeperCoder** [bakwc/LibQtScreen#7]
В данной строке выскакивает ошибка, описанная в топике.
     
`Send(CMD_Info, QByteArray::fromStdString(out.str()));`

QTCreator 3.50 на базе QT 5.5.0

**Comment by bakwc** [comment]
Точно ли версия самой библиотеки Qt 5.5.0? Судя по ошибке - похоже на более старую версию. Версию Qt можно посмотреть в настройках QtCreator-а, http://pastexen.com/i/xhTLKZYRWh.jpg
